# Generated by Django 5.0.1 on 2024-01-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='type',
            new_name='instrument_type',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
