# Generated by Django 5.0.1 on 2024-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0003_alter_musician_instrument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
